import type { IntegrationDefinition } from "./types";

const CLIENTS = {
  auto: ["codex", "claude-code", "claude-desktop", "opencode", "cursor"],
  partial: ["kiro", "cline", "roo", "continue", "kilo", "factory"],
  guided: ["zcode", "generic"],
} as const;

function support(auto: readonly string[], partial: readonly string[] = [], guided: readonly string[] = []) {
  return [
    ...auto.map(clientId => ({ clientId, grade: "auto" as const })),
    ...partial.map(clientId => ({ clientId, grade: "partial" as const })),
    ...guided.map(clientId => ({ clientId, grade: "guided" as const })),
  ];
}

/**
 * Static catalog only. Authentication and connection state live separately so
 * the GUI can render useful choices without exposing secrets.
 */
export const AURA_INTEGRATIONS: readonly IntegrationDefinition[] = [
  {
    id: "github",
    name: "GitHub",
    category: "code",
    description: "Repositories, pull requests, issues, reviews, and project context.",
    authModes: ["oauth2", "mcp", "api-key"],
    capabilities: ["read", "write", "admin"],
    upstream: "official-mcp",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
    docsUrl: "https://github.com/github/github-mcp-server",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "code",
    description: "Projects, merge requests, issues, and repository context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write", "admin"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "code",
    description: "Repositories, pull requests, issues, and source context.",
    authModes: ["oauth2", "api-key"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "backend",
    description: "Database, authentication, storage, edge functions, and project docs.",
    authModes: ["oauth2", "mcp", "api-key"],
    capabilities: ["read", "write", "migration", "admin"],
    upstream: "official-mcp",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
    docsUrl: "https://supabase.com/docs/guides/ai-tools/mcp",
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "backend",
    description: "Firebase projects, Firestore, rules, functions, and documentation.",
    authModes: ["oauth2", "mcp", "cli"],
    capabilities: ["read", "write", "migration", "admin"],
    upstream: "official-mcp",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
    docsUrl: "https://firebase.google.com/docs/ai-assistance/mcp-server",
  },
  {
    id: "neon",
    name: "Neon",
    category: "backend",
    description: "Serverless Postgres projects, branches, schema, and query context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write", "migration", "admin"],
    upstream: "official-mcp",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "backend",
    description: "A guarded connection to a PostgreSQL database or local instance.",
    authModes: ["api-key", "mcp"],
    capabilities: ["read", "write", "migration"],
    upstream: "generic-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "deploy",
    description: "Projects, deployments, environment context, and deployment status.",
    authModes: ["oauth2", "cli", "mcp", "api-key"],
    capabilities: ["read", "write", "deploy", "admin"],
    upstream: "official-mcp",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
    docsUrl: "https://vercel.com/docs/agent-resources/vercel-mcp",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "deploy",
    description: "Sites, deploy previews, environment context, and build status.",
    authModes: ["oauth2", "cli", "api-key"],
    capabilities: ["read", "write", "deploy"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "deploy",
    description: "Workers, Pages, domains, and deployment context.",
    authModes: ["oauth2", "cli", "api-key", "mcp"],
    capabilities: ["read", "write", "deploy", "admin"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "monitoring",
    description: "Errors, traces, releases, and debugging context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "logtail",
    name: "Logtail",
    category: "monitoring",
    description: "Application logs and operational debugging context.",
    authModes: ["api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "generic-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "linear",
    name: "Linear",
    category: "project",
    description: "Issues, projects, cycles, and engineering context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "jira",
    name: "Jira",
    category: "project",
    description: "Issues, boards, releases, and project context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "notion",
    name: "Notion",
    category: "project",
    description: "Pages, databases, project notes, and team context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "slack",
    name: "Slack",
    category: "communication",
    description: "Searchable team context, channels, and selected notifications.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "official-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
  {
    id: "discord",
    name: "Discord",
    category: "communication",
    description: "Selected channels and operational team context.",
    authModes: ["oauth2", "api-key", "mcp"],
    capabilities: ["read", "write"],
    upstream: "generic-api",
    clientSupport: support(CLIENTS.auto, CLIENTS.partial, CLIENTS.guided),
  },
];

export function getIntegrationDefinition(id: string): IntegrationDefinition | undefined {
  return AURA_INTEGRATIONS.find(integration => integration.id === id);
}

